# Generated by Django 3.1.2 on 2020-10-25 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('temperature', models.IntegerField(default=0)),
                ('company', models.CharField(max_length=150)),
                ('id_no', models.CharField(max_length=150, null=True)),
                ('telephone', models.CharField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
